### ISSUE TITLE
error in last step of  using predict_mt_chembl.py for binding affinity prediction

### ISSUE THREAD

**Issue by Hespter** [zjujdj/MetalProGNet#2]
complex ../top1_pose_sdf/7kk4_20_-117.1620.sdf generation failed...
complex ../top1_pose_sdf/7kk4_44_-95.7014.sdf generation failed...
sh: 1: chimera: not found
complex ../top1_pose_sdf/4nw6_45_-65.2051.sdf generation failed...
sh: 1: chimera: not found
complex ../top1_pose_sdf/4nw6_21_-88.2664.sdf generation failed...
sh: 1: chimera: not found
complex ../top1_pose_sdf/7kk4_18_-91.9777.sdf generation failed...
sh: 1: chimera: not found
complex ../top1_pose_sdf/4nw6_1_-93.6212.sdf generation failed...
complex ../top1_pose_sdf/7kk4_16_-95.0478.sdf generation failed...
sh: 1: chimera: not found
sh: 1: chimera: not found
complex ../top1_pose_sdf/7kk4_33_-105.1240.sdf generation failed...
complex ../top1_pose_sdf/4nw6_12_-99.1009.sdf generation failed...
rm: missing operand
Try 'rm --help' for more information.
step1 process end (time:0.14575886726379395 S)

step2 process start: generating dgl graphs
rm: missing operand
Try 'rm --help' for more information.
step2 process end (time:0.12629079818725586 S)

step3 process start: making bin files
the number of successful processed samples is: 0
rm: missing operand
Try 'rm --help' for more information.
step3 process end (time:0.0024900436401367188 S)

step4 process start: making predictions
Loading previously saved dgl graphs and corresponding data...
bin_file: ../temp/bin_files/0.bin data_points: 0
Traceback (most recent call last):
  File "predict_mt_chembl.py", line 657, in <module>
    test_pred = np.concatenate(np.array(test_pred), 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

**Comment by zjujdj** [comment]
@Hespter ,
    Hi, there is no chimera in your environment, you can install it according to this link: https://www.cgl.ucsf.edu/chimera/download.html

**Comment by Hespter** [comment]
> @Hespter , Hi, there is no chimera in your environment, you can install it according to this link: https://www.cgl.ucsf.edu/chimera/download.html

Thanks very much!  After installed chimera ,there is no error of "sh: 1: chimera: not found", but I have another new exception as followed:
 step1 process start: pocket truncation using chimera
Error writing preferences file: /home/wuguangnan/.chimera/preferences:
OSError: [Errno 2] No such file or directory
File "/home/wuguangnan/.local/UCSF-Chimera64-1.17.3/share/CGLutil/SafeSave.py", line 103, in _replace_file
os.rename(self.tmpname, self.filename)
See reply log for Python traceback.
step1 process end (time:11.467841625213623 S)
step2 process start: generating dgl graphs
step2 process end (time:4.146821737289429 S)
step3 process start: making bin files
the number of successful processed samples is: 100
step3 process end (time:0.4109206199645996 S)
step4 process start: making predictions
Loading previously saved dgl graphs and corresponding data...
bin_file: ../temp/bin_files/4.bin data_points: 5
Traceback (most recent call last):
File "predict_mt_chembl.py", line 654, in <module>
test_pred, test_keys = run_a_eval_epoch(DTIModel, test_dataloader, device)
File "predict_mt_chembl.py", line 344, in run_a_eval_epoch
outputs, weights = model(bg, bg3)
File "/home/wuguangnan/anaconda3/envs/dgl430_py37_gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in call
result = self.forward(*input, **kwargs)
File "/home/wshuang/demo/AIDD/MetalProGNet-master/scripts/model_v2.py", line 811, in forward
atom_feats = self.cov_graph(bg, atom_feats, bond_feats)
File "/home/wuguangnan/anaconda3/envs/dgl430_py37_gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in call
result = self.forward(*input, **kwargs)
File "/home/wshuang/demo/AIDD/MetalProGNet-master/scripts/model_v2.py", line 564, in forward
sum_node_feats = self.gnn(g, node_feats, edge_feats)
File "/home/wuguangnan/anaconda3/envs/dgl430_py37_gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in call
result = self.forward(*input, **kwargs)
File "/home/wshuang/demo/AIDD/MetalProGNet-master/scripts/model_v2.py", line 540, in forward
self.sum_node_feats = self.sum_node_feats + node_feats
RuntimeError: CUDA error: no kernel image is available for execution on the device

I am not sure the error of "Error writing preferences file: /home/wuguangnan/.chimera/preferences" whether will affect the final result, but the last error of "RuntimeError: CUDA error: no kernel image is available for execution on the device" have fixed by reinstall the right torch version that match the cuda. But after re-executing the last step of using predict_mt_chembl.py for binding affinity prediction,  a new error message appeared as followed:

Using backend: pytorch
Segmentation fault (core dumped)
  
Could you help me to analyze why this error occurs? Thanks a lot!

**Comment by zjujdj** [comment]
@Hespter 
Hi, i guess the error:"File "/home/wuguangnan/.local/UCSF-Chimera64-1.17.3/share/CGLutil/SafeSave.py"" still come from chimera, and the error "Segmentation fault (core dumped)" comes from your environment.

**Comment by Hespter** [comment]
> @Hespter Hi, i guess the error:"File "/home/wuguangnan/.local/UCSF-Chimera64-1.17.3/share/CGLutil/SafeSave.py"" still come from chimera, and the error "Segmentation fault (core dumped)" comes from your environment.

OK, I will try to reinstall chimera and reconfigure my environment again, thanks a lot!
